name: auto-versioning
run-name: updating version
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
