name: Read PR Body
run-name: reading PR

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: install ollama
      run: curl -fsSL https://ollama.com/install.sh | sh 
    - name: download llama2
      run: ollama pull llama2
    - name: start llama2
      run: ollama serve
      continue-on-error: true
    - name: say hello
      run: echo "Hello World"
    - name: get diff
      run: git diff origin/master HEAD

