name: Read PR Body
run-name: reading PR

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  get_diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
#    - name: install ollama
#      run: curl -fsSL https://ollama.com/install.sh | sh 
#    - name: download llama2
#      run: ollama pull llama2
#    - name: start llama2
#      run: ollama serve
#      continue-on-error: true
     - name: checkout
       uses: actions/checkout@v4
     - name: prepare folder for file
       run: mkdir SRS_files
     - name: fetch
       run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
     - name: diff
       working-directory: SRS_files
       run: git diff --output=diff.txt origin/main HEAD
# [ tu bedzie zadawanie promptow llamie aka puszczenie naszego programu ]
     - name: just testing - gonna change later on
       working-directory: SRS_files
       run: echo "Hi! Wassup? :D" > comment.txt
# ---------------------------------
     - name: comment PR
       uses: thollander/actions-comment-pull-request@v2.5.0
       with:
         filePath: /SRS_files/comment.txt
         pr_number: ${{github.event.number}}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: clean up
       run: rm -r SRS_files
