name: Read PR Body
run-name: reading PR

on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  review-system:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
     - name: checkout
       uses: actions/checkout@v4
  # [ przygotowanie llamy ]
     - name: install ollama
       run: curl -fsSL https://ollama.com/install.sh | sh 
     - name: download llama3
       run: ollama pull llama3
     - name: start llama3
       run: ollama serve
       continue-on-error: true
 # [ przygotowanie pdm - tego pewnie kiedy nie bedzie - chcemy miec w przyszlosci Dockera i skompilowana paczke pythonowa ]
     - name: install pdm
       run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -
     - name: prepare pdm
       working-directory: project
       run: pdm install
 # [ przygotowanie srodowiska do pracy ]
     - name: prepare folder for file
       working-directory: project
       run: mkdir SRS_files
     - name: fetch
       run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
     - name: identify changed python files
       working-directory: project/SRS_files
       run: git diff --name-only origin/main HEAD | grep '\.py$' > changed_files.txt
     - name: create diff file
       working-directory: project/SRS_files
       run: touch diff.txt
     - name: put data in diff file
       run: |
         for file in $(cat project/SRS_files/changed_files.txt); do
           echo >> project/SRS_files/diff.txt
           echo "# File: $file" >> project/SRS_files/diff.txt
           git diff origin/main HEAD -- $file >> project/SRS_files/diff.txt
         done
     - name: debug cat diff.txt
       working-directory: project/SRS_files
       run: cat diff.txt
     - name: create context file
       working-directory: project/SRS_files
       run: touch context.txt
     - name: put data in context file
       run: |
         for file in $(cat project/SRS_files/changed_files.txt); do
           echo >> project/SRS_files/context.txt
           echo "# File: $file" >> project/SRS_files/context.txt
           if [ -f "$file" ]; then
             cat "$file" >> project/SRS_files/context.txt
           else
             echo "File '$file' was deleted or moved." >> project/SRS_files/context.txt
           fi
         done
     - name: debug cat context.txt
       working-directory: project/SRS_files
       run: cat context.txt
 # [ zadawanie promptow llamie ]
     - name: prepare package
       working-directory: project
       run: pdm build
     - name: install package
       working-directory: project
       run: pip install dist/project-0.1.0-py3-none-any.whl
     - name: set python path
       working-directory: project
       run: export PYTHONPATH=$PWD/src
     - name: run prompt-1
       working-directory: project
       run: python -m project
 # [ dodanie komentarza ]
     - name: comment PR
       uses: thollander/actions-comment-pull-request@v2.5.0
       with:
         filePath: project/SRS_files/comment.txt
         pr_number: ${{github.event.number}}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 # [ posprzatanie srodowiska po pracy ]
     - name: clean up
       working-directory: project
       run: rm -r SRS_files
