name: run-unit-tests
run-name: ${{ github.actor }} is running unit tests

on:
  push:
    paths:
      - '**.py'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install pdm
      run: curl -sSL https://pdm-project.org/install-pdm.py | python3 -
    - name: prepare pdm
      run: cd project/
      run: pdm install
    - name: run pytest
      run: pdm run pytest
