name: run-unit-tests
run-name: ${{ github.actor }} is running unit tests

on:
  push:
    paths:
      - '**.py'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: pytest
      run: pdm run pytest
